### ISSUE TITLE
Ridge Racer 2 GRIP cymbals

### ISSUE THREAD

**Issue by RingoStarr39** [superctr/QuattroPlay#11]
Hi there. I just noticed when I was listening to sanodg's "GRIP" on Ridge Racer 2 that the little cymbal splashes that pan left to right starting around 2:35 don't sound correct compared to the Namco Game Sound Express CD and on Ridge Racer Revolution which I believe was a direct rip from the PCB. I'm not sure if this can be fixed but I wanted to bring it to your attention.
[Grip sample.zip](https://github.com/superctr/QuattroPlay/files/3490431/Grip.sample.zip)

**Comment by superctr** [comment]
Actually I noticed this a long time ago, I think they just used different hardware/sound driver combination (likely NB-1/C75) to record the OST. I attach an ini file that forces this combination.
[ridgera2.zip](https://github.com/superctr/QuattroPlay/files/3494214/ridgera2.zip)

More specifically, it's because the cymbals use out of range pitch values. Exactly how this is handled depends on the sound driver version and type (mainly determined `type` variable in the ini file) and the global transpose values (the value of this is set by the ROM and often depends on the hardware).

For examples, the samples might all be tuned for 24.576 MHz chip clock in the sample table, and then adjusted for 25.4016 MHz using the global transpose. For System 22 games, the transpose value is almost always 0, but it differs for other platforms.
