### ISSUE TITLE
The music won`t work on Windows XP.

### ISSUE THREAD

**Issue by RetingencyPlan** [superctr/QuattroPlay#2]
So I have VirtualBox with me, and I have Windows XP as a virtual machine.

But when I execute **quattroplay** on Windows XP, when I get to select a song from some playlist of a game... it plays nothing instead. This didn`t happen on newer Windows systems from what I remember.

**Comment by superctr** [comment]
I can't test it on windows xp myself, so this might be a bit of a pain to diagnose and fix. Which version do you have? Is it the latest build from the releases section? Since the last release I have improved audio device behavior (including adding a device selection menu accessible by pressing f1 in the game selection menu).

Does music play with any application? if not then check that the output device in windows is correct.

**Comment by RetingencyPlan** [comment]
"Which version do you have?"
v1.1-alpha2

"Is it the latest build from the releases section?"
Of course it is.

"Does music play with any application? if not then check that the output device in windows is correct."
All I have from "output device" is "Intel(r) Integrated Audio". That`s it.

**Comment by superctr** [comment]
Please test this binary
[Release.zip](https://github.com/superctr/QuattroPlay/files/825090/Release.zip)

**Comment by RetingencyPlan** [comment]
It plays well with this binary, however it plays a bit slowly I`m afraid(that might be the specifications I set for my VirtualBox machine; 128MB VRAM and 2048MB RAM).

**Comment by superctr** [comment]
thanks for the check. You can adjust the buffer size in `quattroplay.ini`, enter a higher value if you have problems with stuttering.

**Comment by RetingencyPlan** [comment]
"You can adjust the buffer size in quattroplay.ini, enter a higher value if you have problems with stuttering."
This actually worked. Thanks!
