### ISSUE TITLE
Mr. Driller channel volume

### ISSUE THREAD

**Issue by RingoStarr39** [superctr/QuattroPlay#7]
I started a new issue for this. As I stated before, channels 6 and 7 for the Results/Name Entry track should be at the same volume. Compare to this recording from the PCB: https://youtu.be/flZ_M8GcQLk?t=3m32s
Unfortunately the recording was in mono but even folded down to mono you can hear the difference.
It sounds exactly the way it should when quad mode is turned on, but when turned off channel 7 is considerably quieter than channel 6. Although it would appear that this is by design since channel 7 has a volume of 60 while channel 6 is at 30, directly from the PCB this doesn't seem to be the case.

**Comment by RingoStarr39** [comment]
I also just noticed that the Mode Select track sounds more accurate in quad mode as well.

**Comment by superctr** [comment]
Ok, I found the reason for this problem. The game has a mono/stereo option in the sound test. This setting will, if set to mono, mask the "panning" value for all channels. This causes the sound balance to change, because, as it happens, channel 7's panning setting is set to "half-way" between FR and RR. If the setting is "stereo", this simply attenuates the sound on the FR speaker.

Currently the mono/stereo setting is implemented in the driver, but not exposed in the UI in any way.

The panning values work like this:
<pre>
FL     Center    FR
 -32 --- 0 --- +32
   |            |
   |            |
   |            |
 -64           +64
   |            |
   |            |
   |            |
 -96 ---   --- +96
RL               RR
</pre>

**Comment by RingoStarr39** [comment]
Wow, I completely forgot about that mono setting. I always assumed it just folded down the stereo output. Maybe F5 could be used to toggle between quad, stereo and mono mode. Thanks for figuring that out. I've read before that Go Shiina had a hard time programming the sound chip, which could account for the odd panning.
